
name: SBOM Generation Workflow

on:
  push:
    branches:
      - main

jobs:
  sbom-ingestion-job:
    runs-on: ubuntu-latest

    env:
      HARNESS_ACCOUNT_URL: 'https://myaccount.harness.io'
      HARNESS_ACCOUNT_ID: '_myaccount_rzPs_JtWT7g'
      HARNESS_ORG_ID: 'SCS'
      HARNESS_PROJECT_ID: 'SCS_ID'
      HARNESS_API_KEY: ${{ secrets.SCS_API_KEY }}
      # VAULT_ADDR: ${{ secrets.VAULT_URL }}

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Log in to Vault
      # - name: Log in to Vault
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ secrets.VAULT_URL }}
      #     method: token
      #     token: ${{ secrets.VAULT_TOKEN }}

      # Step 6: Run SBOM Ingestion
      - name: Run SBOM Ingestion Action
        uses: harness/github-actions/sbom-ingestion@v1.0.0
        with:
          TARGET: image/myimagetag
          SBOM_FILE_PATH: '/harness/shared/sbom.json'
          ATTEST: true
          KMS_KEY: 'path/to/my/key/in/vault'

