
name: SBOM Generation Workflow

on:
  push:
    branches:
      - main

jobs:
  sbom-generation-job:
    runs-on: ubuntu-latest

    env:
      HARNESS_ACCOUNT_URL: 'https://app.harness.io'
      HARNESS_ACCOUNT_ID: 'vpCkHKsDSxK9_KYfjCTMKA'
      HARNESS_ORG_ID: 'SSCA'
      HARNESS_PROJECT_ID: 'Exploratory'
      HARNESS_API_KEY: ${{ secrets.SCS_API_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_URL }}

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Tag Docker Image
      - name: Build and Tag Docker Images
        run: |
          
          docker build -t lavakush07/easy-buggy-app:GHA1 .
          echo "Docker image built and tagged as lavakush07/easy-buggy-app:GHA1."

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push lavakush07/easy-buggy-app:GHA1
          echo "Docker image pushed to Docker Hub."
          

      # Step 5: Log in to Vault
      - name: Log in to Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}

      # Step 6: Run SBOM Generation and Attestation
      - name: Run SBOM Generation Action
        uses: ./sbom-generation
        with:
          TOOL: 'Syft'
          FORMAT: 'spdx-json'
          TARGET: 'lavaksuh07/easy-buggy-app:GHA1'
          ATTEST: true
          KMS_KEY: 'cosign'

